#!/usr/bin/env bash
# Author: Jacqueline Garrahan
#
# Start alarm logger service
#
# Copyright @2021 SLAC National Accelerator Laboratory
if [ "$1" == "-h" ]; then
  echo "Usage: start-logger config_name config_file"
  echo "Requires setting \$LOGGING_CONFIG_FILE, \$ALARM_LOGGER_PROPERTIES, \$ALARM_LOGGER_JAR, \$ES_HOST, \$ES_PORT, \$BOOTSTRAP_SERVERS"
  exit 0
fi

if [[ -z "$LOGGING_CONFIG_FILE" ]]; then
  echo "Logging configuration file not defined. Please set \$LOGGING_CONFIG_FILE."
  exit 0
fi

if [[ -z "$ALARM_LOGGER_PROPERTIES" ]]; then
  echo "Alarm logger properties file not defined. Please set \$ALARM_LOGGER_PROPERTIES."
  exit 0
fi

if [[ -z "$ALARM_LOGGER_JAR" ]]; then
  echo "Alarm logger jar file not defined. Please set \$ALARM_LOGGER_JAR."
  exit 0
fi

if [[ -z "$ES_HOST" ]]; then
  echo "Elasticsearch host not defined. Please set \$ES_HOST."
  exit 0
fi

if [[ -z "$ES_PORT" ]]; then
  echo "Elasticsearch port not defined. Please set \$ES_PORT."
  exit 0
fi

if [[ -z "$BOOTSTRAP_SERVERS" ]]; then
  echo "Bootstrap servers not defined. Please set \$BOOTSTRAP_SERVERS."
  exit 0
fi



CONFIG_NAME=$1
CONFIG_FILE=$2

sed -i 's/$ES_HOST/'"$ES_HOST/" $ALARM_LOGGER_PROPERTIES
sed -i 's/$ES_PORT/'"$ES_PORT/" $ALARM_LOGGER_PROPERTIES
sed -i 's/$BOOTSTRAP_SERVERS/'"$BOOTSTRAP_SERVERS/" $ALARM_LOGGER_PROPERTIES


java -jar $ALARM_LOGGER_JAR -properties $ALARM_LOGGER_PROPERTIES -topics $CONFIG_NAME -noshell
