---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-alrm-send-cryo
  labels:
    app: loki-alrm-send-cryo
    app.kubernetes.io/name: loki-alarm-sender
    app.kubernetes.io/part-of: nalms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-alrm-send-cryo
  template:
    metadata:
      labels:
        app: loki-alrm-send-cryo
        app.kubernetes.io/name: loki-alarm-sender
        app.kubernetes.io/part-of: nalms
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values: [loki-alarm-sender]
                topologyKey: kubernetes.io/hostname
      containers:
        - name: loki-alrm-send-cryo
          image: tidacs/nalms-loki-alarm-sender:v1.0
          args:
            - --topics
            - CRYO,CRYOCommand
            - --bootstrap-servers
            - nalms-kafka-bootstrap:9092
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: SLACK_WEBHOOK_URL
      restartPolicy: Always
