#!/usr/bin/env bash
set -e
export CLI_WORKDIR=$(cd $(dirname $0) && pwd)
. "$CLI_WORKDIR/common"


cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
NALMS CLI
Usage: $cli_name [command]
Commands:
  start-alarm-server config_name config_file [--properties server_properties] [--logging_properties logging_config]
  start-alarm-logger config_name config_file [--properties logger_properties] [--logging_properties logging_config]
  start-alarm-ioc config_name config_file
  start-cruise-control [--properties property_file]
  start-elasticsearch [--port elasticsearch]
  start-kafka-broker [--properties property_file] [--port kafka_port] [--broker_number number]
  start-phoebus-client [--properties property_file]
  start-grafana [--port grafana_port]
  create-alarm-ioc configuration_file config_name output_directory
  convert-alh alh_file output_filename config_name
  list-configurations
  launch-editor
  convert-alh
  *         Help
"
  exit 0
}

case "$1" in
  start-alarm-server|d)
    . "$CLI_WORKDIR/commands/start-alarm-server" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"| tee -ia "$CLI_WORKDIR/start-alarm-server_${2}.log"
    ;;
  start-alarm-logger|d)
    . "$CLI_WORKDIR/commands/start-alarm-logger" "$2" "$3" "$4" "$5" "$6" "$7" | tee -ia "$CLI_WORKDIR/start-alarm-logger_$2.log"
    ;;
  start-kafka-broker|d)
    . "$CLI_WORKDIR/commands/start-kafka-broker" "$2" "$3" "$4" "$5" "$6"| tee -ia "$CLI_WORKDIR/start-kafka-broker.log"
    ;;
  start-zookeeper|d)
    . "$CLI_WORKDIR/commands/start-zookeeper" "$2" "$3" | tee -ia "$CLI_WORKDIR/start-zookeper.log"
    ;;
  start-elasticsearch|d)
    . "$CLI_WORKDIR/commands/start-elasticsearch" "$2" "$3"| tee -ia "$CLI_WORKDIR/start-elasticsearch.log"
    ;;
  start-cruise-control|d)
    . "$CLI_WORKDIR/commands/start-cruise-control" "$2" "$3"| tee -ia "$CLI_WORKDIR/start-cruise-control.log"
    ;;
  start-phoebus-client|d)
    . "$CLI_WORKDIR/commands/start-phoebus-client" | tee -ia "$CLI_WORKDIR/start-phoebus-client.log"
    ;;
  start-grafana|d)
    . "$CLI_WORKDIR/commands/start-grafana" | tee -ia "$CLI_WORKDIR/start-grafana.log"
    ;;
  create-alarm-ioc|d)
    . "$CLI_WORKDIR/commands/create-alarm-ioc" "$2" "$3" "$4"  | tee -ia "$CLI_WORKDIR/create-alarm-ioc.log"
    ;;
  convert-alh|d)
    . "$CLI_WORKDIR/commands/convert-alh" "$2" "$3" "$4" | tee -ia "$CLI_WORKDIR/convert-alh.log"
    ;;
  list-configurations|d)
    . "$CLI_WORKDIR/commands/list-configurations"
    ;;
  launch-editor|d)
    . "$CLI_WORKDIR/commands/launch-editor"
    ;;
  *)
    cli_help
    ;;
esac