#!/usr/bin/env bash
set -e
export CLI_WORKDIR=$(cd $(dirname $0) && pwd)
. "$CLI_WORKDIR/common"


cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
NALMS CLI
Usage: $cli_name [command]
Commands:
  start-alarm-server config_name config_file
  start-alarm-logger config_name config_file 
  start-alarm-ioc config_name config_file
  start-cruise-control
  start-elasticsearch [--port elasticsearch]
  start-kafka-broker [--properties property_file] [--port kafka_port] [--broker_number number]
  start-phoebus-client config_name
  start-grafana [--port grafana_port]
  create-alarm-ioc configuration_file config_name output_directory
  convert-alh alh_file output_filename config_name
  delete-configurations configuration_name
  list-configurations
  launch-editor
  generate-kafka-certs domain password
  convert-alh
  *         Help
"
  exit 0
}

case "$1" in
  start-alarm-server|d)
    . "$CLI_WORKDIR/commands/start-alarm-server" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
    ;;
  start-alarm-logger|d)
    . "$CLI_WORKDIR/commands/start-alarm-logger" "$2" "$3" 
    ;;
  start-kafka-broker|d)
    . "$CLI_WORKDIR/commands/start-kafka-broker" "$2" "$3" "$4" "$5" "$6"
    ;;
  start-zookeeper|d)
    . "$CLI_WORKDIR/commands/start-zookeeper" "$2" "$3" 
    ;;
  start-elasticsearch|d)
    . "$CLI_WORKDIR/commands/start-elasticsearch" "$2" "$3" 
    ;;
  start-cruise-control|d)
    . "$CLI_WORKDIR/commands/start-cruise-control" 
    ;;
  start-phoebus-client|d)
    . "$CLI_WORKDIR/commands/start-phoebus-client" "$2"
    ;;
  start-grafana|d)
    . "$CLI_WORKDIR/commands/start-grafana" 
    ;;
  create-alarm-ioc|d)
    . "$CLI_WORKDIR/commands/create-alarm-ioc" "$2" "$3" "$4" 
    ;;
  convert-alh|d)
    . "$CLI_WORKDIR/commands/convert-alh" "$2" "$3" "$4" 
    ;;
  generate-kafka-certs|d)
    . "$CLI_WORKDIR/commands/generate-kafka-certs" "$2" "$3" 
    ;;
  list-configurations|d)
    . "$CLI_WORKDIR/commands/list-configurations"
    ;;
  delete-configuration|d)
    . "$CLI_WORKDIR/commands/delete-configuration" "$2"
    ;;
  launch-editor|d)
    . "$CLI_WORKDIR/commands/launch-editor"
    ;;
  *)
    cli_help
    ;;
esac