#!/bin/bash
ALARM_APP_NAME=$1
SOFT_IOC_NAME=$2
CONFIGURATION_FILE=$4
CONFIG_NAME=$3
 
mkdir $ALARM_APP_NAME

cd $ALARM_APP_NAME
 
makeBaseApp.pl -t ioc $ALARM_APP_NAME
makeBaseApp.pl -i -t ioc -a rhel6-x86_64 -p $ALARM_APP_NAME $SOFT_IOC_NAME

# create alarm db file from nalms-tools script
mkdir /tmp/nalms/$SOFT_IOC_NAME
create-soft-ioc $CONFIGURATION_FILE /tmp/nalms/$SOFT_IOC_NAME $CONFIG_NAME

# save summary pvs and add to makefile
SUMMARY_PV_FILE=nalms_${CONFIG_NAME}.db 
mv /tmp/nalms/$SOFT_IOC_NAME/$SUMMARY_PV_FILE $ALARM_APP_NAME/Db/$SUMMARY_PV_FILE
echo "DB += ${SUMMARY_PV_FILE}" >> $ALARM_APP_NAME/Db/Makefile

# save substitutions and add to makefile
SUBSTITUTIONS_FILE=nalms_${CONFIG_NAME}.substitutions 
mv /tmp/nalms/$SOFT_IOC_NAME/$SUBSTITUTIONS_FILE $ALARM_APP_NAME/Db/$SUBSTITUTIONS_FILE
echo "DB += ${SUBSTITUTIONS_FILE}" >> $ALARM_APP_NAME/Db/Makefile

# save force pv template
TEMPLATE_FILE=force_pv.template 
mv /tmp/nalms/$SOFT_IOC_NAME/$TEMPLATE_FILE $ALARM_APP_NAME/Db/$TEMPLATE_FILE
echo "DB += ${TEMPLATE_FILE}" >> $ALARM_APP_NAME/Db/Makefile

sed '14 i dbLoadRecords("db/${SUMMARY_PV_FILE}"' ioc$SOFT_IOC_NAME
sed '14 i dbLoadTemplate("db/${SUBSTITUTIONS_FILE}"' ioc$SOFT_IOC_NAME