#!/bin/bash
ALARM_APP_NAME=$1
SOFT_IOC_NAME=$2
CONFIGURATION_FILE=$4
CONFIG_NAME=$3
EPICS_SETUP=$5


# use nalms python environment
create-soft-ioc $CONFIGURATION_FILE /tmp/nalms/$SOFT_IOC_NAME $CONFIG_NAME

# source epics environment
source $EPICS_SETUP

mkdir $ALARM_APP_NAME

cd $ALARM_APP_NAME
 
makeBaseApp.pl -t ioc $ALARM_APP_NAME
makeBaseApp.pl -i -t ioc -a rhel6-x86_64 -p $ALARM_APP_NAME $SOFT_IOC_NAME

# create alarm db file from nalms-tools script
mkdir -p /tmp/nalms/$SOFT_IOC_NAME
# save summary pvs and add to makefile
SUMMARY_PV_FILE=nalms_${CONFIG_NAME}.db 
mv /tmp/nalms/$SOFT_IOC_NAME/$SUMMARY_PV_FILE ${ALARM_APP_NAME}App/Db/$SUMMARY_PV_FILE
sed -i '10 i DB += '"$SUMMARY_PV_FILE" ${ALARM_APP_NAME}App/Db/Makefile

# save substitutions and add to makefile
SUBSTITUTIONS_FILE=nalms_${CONFIG_NAME}.substitutions 
mv /tmp/nalms/$SOFT_IOC_NAME/$SUBSTITUTIONS_FILE ${ALARM_APP_NAME}App/Db/$SUBSTITUTIONS_FILE
sed -i '11 i DB += '"$SUBSTITUTIONS_FILE" ${ALARM_APP_NAME}App/Db/Makefile

# save force pv template
TEMPLATE_FILE=nalms_force_pv.template 
mv /tmp/nalms/$SOFT_IOC_NAME/$TEMPLATE_FILE ${ALARM_APP_NAME}App/Db/$TEMPLATE_FILE
sed -i '12 i DB += '"$TEMPLATE_FILE" ${ALARM_APP_NAME}App/Db/Makefile


# drop the pre-built record...
sed -i '/dbLoadRecords/d' iocBoot/ioc$SOFT_IOC_NAME/st.cmd
sed -i '13 i dbLoadRecords("../../db/'"$SUMMARY_PV_FILE"'")' iocBoot/ioc$SOFT_IOC_NAME/st.cmd
sed -i '13 i dbLoadTemplate("../../db/'"$SUBSTITUTIONS_FILE"'")' iocBoot/ioc$SOFT_IOC_NAME/st.cmd