#!/usr/bin/env bash
#
# Author: Jacqueline Garrahan
# Create alarm ioc files for a given configuration_file
# Requires nalms-tools to be installed into active python environment
usage() {
  cli_name=${0##*/}
  echo "Usage: nalms create-alarm-ioc configuration_file config_name output_directory"
  exit 0
}

if [[ "$1" == "-h" ]]; then
  usage
fi

if [[ -z "$1" ]]; then
  usage
else
  CONFIG_FILE="$1"
fi

if [[ -z "$2" ]]; then
  usage
else
  CONFIG_NAME="$2"
fi

if [[ -z "$3" ]]; then
  usage
else
  OUTPUT_DIR="$3"
fi


#makeBaseApp.pl -t ioc $CONFIG_NAME
#makeBaseApp.pl -a rhel6-x86_64 -p $CONFIG_NAME -i -t ioc sioc-nalms-heartofgold



create-soft-ioc $CONFIG_FILE $OUTPUT_DIR $CONFIG_NAME