#!/bin/sh
# Author: Jacqueline Garrahan
#
# List active configurations tracked with a zookeeper host.
#
# Copyright @2021 SLAC National Accelerator Laboratory

if [ "$1" == "-h" ]; then
  echo "Usage: list-configurations"
  echo "Requires \$KAFKA_HOME and \$KAFKA_BOOTSTRAP to be set."
  exit 0
fi

if [[ ! -d "$KAFKA_HOME" ]]; then
  echo "KAFKA_HOME is not set."
  exit 0
fi

if [[ -z "$KAFKA_BOOTSTRAP" ]]; then
  echo "KAFKA_BOOTSTRAP is not set."
  exit 0
fi

list_var=$($KAFKA_HOME/bin/kafka-topics.sh --list --bootstrap-server $KAFKA_BOOTSTRAP)
echo $list_var
IFS=$'\n'

read -rd '' -a strarr <<< "$list_var"

for val in "${strarr[@]}";
do
#    if  [ grep -q "Command" <<< "$val" ] && [ grep -q "Talk"  <<< "$val" ] ; then
    if [[ ! "$val" == *"Command" && ! "$val" == *"Talk" && ! "$val" == *"Metrics" && ! "$val" == *"consumer_offsets" ]]; then
    # && "Talk" != *"$val"*
      echo "$val";
    fi
done
