#!/usr/bin/env bash
#
# Author: Jacqueline Garrahan
# Run elasticsearch instance

usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-elasticsearch [--port elasticsearch]"
  echo "Port required, but may be set using the \$NALMS_ES_PORT environment variable."
  echo "\$NALMS_ES_CONFIG must be set."
  exit 0
}

# parse optional items
while test $# -gt 0
do
    case "$1" in
        --port) 
          NALMS_ES_PORT=$2
            ;;
        "")
    esac
    shift
done

if [[ -z "$NALMS_ES_PORT" ]]; then
  echo "No port provided for Elasticsearch."
  usage
fi

if [[ -z "$NALMS_ES_CONFIG" ]]; then
  echo "No configuration file provided for Elasticsearch. Define \$NALMS_ES_CONFIG"
  usage
fi


docker run \
    -e node.name=node01 \
    -e cluster.name=es-cluster-7 \
    -e discovery.type=single-node \
    -e ES_JAVA_OPTS="-Xms128m -Xmx128m" \
    -e ES_HOST=localhost \
    -e ES_PORT=9200 \
    -v "${NALMS_ES_CONFIG}:/usr/share/elasticsearch/config" \
    -p "$NALMS_ES_PORT:9200" \
    --name nalms_elasticsearch \
    -d jgarrahan/nalms-elasticsearch:latest
