#!/bin/bash
#
# Author: Jacqueline Garrahan
# Run grafana instance

usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-grafana [--port grafana_port]"
  echo "Requires definition of \$NALMS_GRAFANA_PORT, \$NALMS_GRAFANA_DASHBOARD_DIR, \$NALMS_GRAFANA_DATASOURCE_FILE, "
  echo "\$NALMS_DOCKER_ES_VERSION, \$NALMS_GRAFANA_CONFIG"
  exit 0
}

# parse optional items
while test $# -gt 0
do
    case "$1" in
        --port) 
          NALMS_GRAFANA_PORT=$2
            ;;
        "")
    esac
    shift
done

if [[ -z "$NALMS_GRAFANA_PORT" ]]; then
  echo "No port provided for Grafana."
  usage
fi
if [[ -z "$NALMS_GRAFANA_DASHBOARD_DIR" ]]; then
  echo "NALMS_GRAFANA_DASHBOARD_DIR not defined."
  usage
fi

if [[ -z "$NALMS_GRAFANA_DATASOURCE_FILE" ]]; then
  echo "NALMS_GRAFANA_DATASOURCE_FILE not defined."
  usage
fi

if [[ -z "$NALMS_GRAFANA_CONFIG" ]]; then
  echo "NALMS_GRAFANA_CONFIG not defined."
  usage
fi

if [[ -z "$NALMS_DOCKER_ES_VERSION" ]]; then
  echo "NALMS_DOCKER_ES_VERSION not defined."
  usage
fi

docker run \
    -p "${NALMS_GRAFANA_PORT}:3000" \
    -v "${NALMS_GRAFANA_DASHBOARD_DIR}:/var/lib/grafana/dashboards" \
    -v "${NALMS_GRAFANA_DATASOURCE_FILE}:/etc/grafana/provisioning/datasources/all.yml" \
    -v "${NALMS_GRAFANA_CONFIG}:/etc/grafana/config.ini" \
    --name nalms_grafana \
    -d tidacs/nalms-grafana:$NALMS_DOCKER_ES_VERSION

