#!/bin/bash
#
# Author: Jacqueline Garrahan
# Run zookeeper image for given configuration

usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-zookeeper [--port zookeeper_port]"
  echo "Port required, but may be set using the \$NALMS_ZOOKEEPER_PORT environment variable."
  echo "Must set \$ NALMS_ZOOKEEPER_CONFIG, \$NALMS_DOCKER_ZOOKEEPER_VERSION"
  exit 0
}


# parse optional items
while test $# -gt 0
do
    case "$1" in
        --port) 
          NALMS_ZOOKEEPER_PORT=$2
            ;;
        "")
    esac
    shift
done

if [[ -z "$NALMS_ZOOKEEPER_PORT" ]]; then
  echo "No port provided for Zookeeper."
  usage
fi

if [[ -z "$NALMS_ZOOKEEPER_CONFIG" ]]; then
  echo "No config provided for Zookeeper. Please set \$NALMS_ZOOKEEPER_CONFIG"
  usage
fi

if [[ -z "$NALMS_DOCKER_ZOOKEEPER_VERSION" ]]; then
  echo "No version provided for Zookeeper. Please set \$NALMS_DOCKER_ZOOKEEPER_VERSION"
  usage
fi


docker run -p "${NALMS_ZOOKEEPER_PORT}:2181" -e ZOOKEEPER_CONFIG=/tmp/zoo.cfg \
  -v "${NALMS_ZOOKEEPER_CONFIG}:/tmp/zoo.cfg" --name nalms_zookeeper \
  -d tidacs/nalms-zookeeper:$NALMS_DOCKER_ZOOKEEPER_VERSION