#!/bin/bash
#
# Author: Jacqueline Garrahan
# Run phoebus-alarm-server image for given configuration
usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-alarm-server config_name config_file"
  exit 0
}

if [[ "$1" == "-h" ]]; then
  usage
fi

if [[ -z "$1" ]]; then
  usage
else
  CONFIG_NAME="$1"
fi

if [[ -z "$2" ]]; then
  usage
else
  CONFIG_FILE="$2"
fi


if [[ -z "$NALMS_KAFKA_BOOTSTRAP" ]]; then
  echo "No Kafka bootstrap provided."
  usage
fi

if [[ -z "$NALMS_ALARM_SERVER_PROPERTIES" ]]; then
  echo "No Kafka bootstrap provided."
  usage
fi

if [[ -z "$NALMS_DOCKER_ALARM_SERVER_VERSION" ]]; then
  echo "NALMS_DOCKER_ALARM_SERVER_VERSION not defined."
  usage
fi

docker run -v $CONFIG_FILE:/tmp/nalms/$CONFIG_NAME.xml \
  --name nalms_server_$CONFIG_NAME \
  -v "${NALMS_ALARM_SERVER_PROPERTIES}:/opt/nalms/config/alarm_server.properties" \
  -e ALARM_IOC=false \
  -e KAFKA_BOOTSTRAP="${NALMS_KAFKA_BOOTSTRAP}" \
  -e EPICS_CA_ADDR_LIST="${EPICS_CA_ADDR_LIST}" \
  -e EPICS_CA_SERVER_PORT="${EPICS_CA_SERVER_PORT}" \
  -e EPICS_CA_REPEATER_PORT="${EPICS_CA_REPEATER_PORT}" \
  -e EPICS_PVA_ADDR_LIST="${EPICS_PVA_ADDR_LIST}" \
  -e EPICS_PVA_SERVER_PORT="${EPICS_PVA_SERVER_PORT}" \
  -e EPICS_PVA_REPEATER_PORT="${EPICS_PVA_REPEATER_PORT}" \
  -e ALARM_SERVER_PROPERTIES="/opt/nalms/config/alarm_server.properties" \
  -d -t jgarrahan/nalms-phoebus-alarm-server:$NALMS_DOCKER_ALARM_SERVER_VERSION start-server $CONFIG_NAME /tmp/nalms/$CONFIG_NAME.xml
