#!/usr/bin/env bash
#
# Author: Jacqueline Garrahan
# Run kafka  image for given configuration

usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-kafka-broker [--port kafka_port] [--broker broker_number]"
  echo "Port and property file required, but may be set using the \$NALMS_KAFKA_PROPERTIES or \$NALMS_KAFKA_PORT environment variables."
  echo "Requires setting \$NALMS_KAFKA_PROPERTIES and \$NALMS_DOCKER_KAFKA_VERSION"
  exit 0
}

BROKER_NUMBER=0

# parse optional items
while test $# -gt 0
do
    case "$1" in
        --properties) 
          NALMS_KAFKA_PROPERTIES=$2
            ;;
        --port) 
          NALMS_KAFKA_PORT=$2
            ;;
        --port) 
          BROKER_NUMBER=$2
            ;;
        "")
    esac
    shift
done

if [[ -z "$NALMS_KAFKA_PROPERTIES" ]]; then
  echo "No property file provided for Kafka broker."
  usage
fi

if [[ -z "$NALMS_KAFKA_PORT" ]]; then
  echo "No port provided for Kafka server."
  usage
fi

if [[ -z "$BROKER_NUMBER" ]]; then
  echo "No port provided for Kafka server."
  usage
fi

if [[ -z "$NALMS_DOCKER_KAFKA_VERSION" ]]; then
  echo "No version provided for Kafka docker."
  usage
fi


docker run -m 8g  \
  -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9091,CONNECTIONS_FROM_HOST://$NALMS_KAFKA_HOST:$NALMS_KAFKA_PORT \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT \
  -e KAFKA_LISTENERS=PLAINTEXT://localhost:9091,CONNECTIONS_FROM_HOST://0.0.0.0:$NALMS_KAFKA_PORT \
  -e ZOOKEEPER_CONNECT=$NALMS_ZOOKEEPER_HOST:$NALMS_ZOOKEEPER_PORT \
  -e BROKER_ID=$BROKER_NUMBER\
  -v "${NALMS_KAFKA_PROPERTIES}:/opt/kafka/server.properties" \
  -p "$NALMS_KAFKA_PORT:$NALMS_KAFKA_PORT" \
  --name nalms_kafka_$BROKER_NUMBER \
  -d jgarrahan/nalms-kafka:$NALMS_DOCKER_KAFKA_VERSION