#!/usr/bin/env bash
#
# Author: Jacqueline Garrahan
# Run phoebus-alarm-logger image for given configuration
#
usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-alarm-logger config_name config_file "
  echo "Requires definition of \$ALARM_LOGGER_PROPERTIES and optional definition of"
  echo "\$NALMS_ES_HOST, \$NALMS_ES_PORT, \$NALMS_BOOTSTRAP_SERVERS"
  exit 0
}

if [[ "$1" == "-h" ]]; then
  usage
fi

if [[ -z "$1" ]]; then
  usage
else
  CONFIG_NAME="$1"
fi

if [[ -z "$2" ]]; then
  usage
else
  CONFIG_FILE="$2"
fi


if [[ -z "$NALMS_ALARM_LOGGER_PROPERTIES" ]]; then
  echo "Property file not provided."
  usage
fi


if [ "$1" == "-h" ]; then
  echo "Usage: deploy-configuration.sh [Configuration Name] [Configuration file] [Alarm logger properties file] [Logging configuration files]"
  exit 0
fi

docker run -v $CONFIG_FILE:/tmp/nalms/$CONFIG_NAME.xml \
  -e ES_HOST="${NALMS_ES_HOST}" \
  -e ES_PORT="${NALMS_ES_PORT}" \
  -e BOOTSTRAP_SERVERS="${NALMS_KAFKA_BOOTSTRAP}" \
  -e ALARM_LOGGER_PROPERTIES="/opt/nalms/config/alarm_logger.properties" \
  -v "${NALMS_ALARM_LOGGER_PROPERTIES}:/opt/nalms/config/alarm_logger.properties" \
  --name nalms_logger_$CONFIG_NAME \
  -d jgarrahan/nalms-phoebus-alarm-logger:latest start-logger $CONFIG_NAME /tmp/nalms/$CONFIG_NAME.xml