#!/usr/bin/env bash
#
# Author: Jacqueline Garrahan
# Run phoebus-alarm-server image for given configuration
usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-alarm-server config_name config_file [--properties server_properties] [--logging_properties logging_config]"
  exit 0
}

if [[ "$1" == "-h" ]]; then
  usage
fi

if [[ -z "$1" ]]; then
  usage
else
  CONFIG_NAME="$1"
fi

if [[ -z "$2" ]]; then
  usage
else
  CONFIG_FILE="$2"
fi

# parse optional items
while test $# -gt 0
do
    case "$1" in
        --properties) 
          NALMS_ALARM_SERVER_PROPERTIES=$2
            ;;
        --logging_properties) 
          NALMS_LOGGING_PROPERTIES=$2
            ;;
        --kafka_bootstrap) 
          NALMS_KAFKA_BOOTSTRAP=$2
            ;;
        "")
    esac
    shift
done

if [[ -z "$NALMS_ALARM_SERVER_PROPERTIES" ]]; then
  echo "No property file provided for alarm server."
  usage
fi

if [[ -z "$NALMS_LOGGING_PROPERTIES" ]]; then
  echo "No property file provided for logging."
  usage
fi


docker run -v $CONFIG_FILE:/tmp/nalms/$CONFIG_NAME.xml \
  -v $NALMS_ALARM_SERVER_PROPERTIES:/opt/nalms/config/alarm_server.properties \
  -v $NALMS_LOGGING_PROPERTIES:/opt/nalms/config/logging.properties \
  -d -t phoebus-alarm-server start-server $CONFIG_NAME /tmp/nalms/$CONFIG_NAME.xml
