#!/usr/bin/env bash
#
# Author: Jacqueline Garrahan
# Run cruise-control image and serve UI
#
usage() {
  cli_name=${0##*/}
  echo "Usage: nalms start-cruise-control"
  echo "Requires definition of \$NALMS_BOOTSTRAP_SERVERS, \$NALMS_ZOOKEEPER_HOST, \$NALMS_ZOOKEEPER_PORT \$NALMS_CRUISE_CONTROL_PORT"
  exit 0
}

if [[ "$1" == "-h" ]]; then
  usage
fi


if [[ -z "$NALMS_KAFKA_BOOTSTRAP" ]]; then
  echo "No bootstrap servers defined for cruise control."
  usage
fi

if [[ -z "$NALMS_ZOOKEEPER_HOST" ]]; then
  echo "No zookeeper host defined for cruise control."
  usage
fi

if [[ -z "$NALMS_ZOOKEEPER_PORT" ]]; then
  echo "No zookeeper host defined for cruise control."
  usage
fi


if [[ -z "$NALMS_CRUISE_CONTROL_PORT" ]]; then
  echo "No cruise control port defined ."
  usage
fi


docker run \
    -e BOOTSTRAP_SERVERS=$NALMS_BOOTSTRAP_SERVERS \
    -e ZOOKEEPER_CONNECT=$NALMS_ZOOKEEPER_HOST:$NALMS_ZOOKEEPER_PORT \
    --name nalms_cruise_control \
    -p "$NALMS_CRUISE_CONTROL_PORT:9090" -d jgarrahan/nalms-cruise-control:latest