#!/usr/bin/env bash
# Author: Jacqueline Garrahan
#
# Create tmux sessions and launch alarm services
#
# Copyright @2021 SLAC National Accelerator Laboratory

EXIT=0

if [ "$1" == "-h" ]; then
  echo "Usage: start-services.sh config_name config_file [--softIoc]"
  exit 0
fi

if [[ -z "$1" || "$1" == "--softIoc" ]]; then
  echo "Configuration name not provided."
  echo "Usage: start-services.sh config_name config_file [--softIoc]"
  exit 0
else
  echo $1
fi

if [[ -z "$2" || "$2" == "--softIoc" ]]; then
  echo "Configuration file not provided."
  echo "Usage: start-services.sh config_name config_file [--softIoc]"
  exit 0
fi


BUILD_SOFTIOC=0
if [[ "$3" == "--softIoc" ]]; then
  BUILD_SOFTIOC=1
fi

if [[ -z "$LOGGING_CONFIG_FILE" ]]; then
  echo "Logging configuration file not defined. Please set \$LOGGING_CONFIG_FILE."
  exit 0
fi

if [[ -z "$ALARM_SERVER_PROPERTIES" ]]; then
  echo "Alarm server properties file not defined. Please set \$ALARM_SERVER_PROPERTIES."
  exit 0
fi

if [[ -z "$ALARM_LOGGER_PROPERTIES" ]]; then
  echo "Alarm logger properties file not defined. Please set \$ALARM_LOGGER_PROPERTIES."
  exit 0
fi

if [[ -z "$ALARM_SERVER_JAR" ]]; then
  echo "Alarm server jar file not defined. Please set \$ALARM_SERVER_JAR."
  exit 0
fi

if [[ -z "$ALARM_LOGGER_JAR" ]]; then
  echo "Alarm logger jar file not defined. Please set \$ALARM_LOGGER_JAR."
  exit 0
fi

if [[ $BUILD_SOFTIOC -eq 1 && -z "$EPICS_BASE" ]]; then
  echo "EPICS base not defined. Please set \$EPICS_BASE."
  exit 0
fi


export PATH="$JAVA_HOME/bin:$PATH"

CONFIG_NAME=$1
CONFIG_FILE=$2

# create nalms session if not running, attach otherwise
if [[ -z $(tmux list-sessions 2>/dev/null | grep nalms) ]]; then
  tmux $TMUX_OPTS new-session -s nalms_$CONFIG_NAME -d
fi

# create config name
tmux new-window -a -t nalms_$CONFIG_NAME -n alarm_server -c $PWD
tmux new-window -a -t nalms_$CONFIG_NAME -n alarm_logger -c $PWD
tmux new-window -a -t nalms_$CONFIG_NAME -n ioc -c $PWD

#create panes
tmux select-layout -t nalms_$CONFIG_NAME tiled > /dev/null

if java -jar $ALARM_SERVER_JAR -logging $LOGGING_CONFIG_FILE -config $CONFIG_NAME -import $CONFIG_FILE; then
  # set up server window 
  tmux send-keys -t nalms_$CONFIG_NAME:alarm_server "export JAVA_HOME=$JAVA_HOME" C-m
  tmux send-keys -t nalms_$CONFIG_NAME:alarm_server "export PATH=$JAVA_HOME/bin:$PATH" C-m
  tmux send-keys -t nalms_$CONFIG_NAME:alarm_server "java -jar $ALARM_SERVER_JAR -config $CONFIG_NAME -logging $LOGGING_CONFIG_FILE -settings $ALARM_SERVER_PROPERTIES" C-m

  # set up logger window
  tmux send-keys -t nalms_$CONFIG_NAME:alarm_logger "export JAVA_HOME=$JAVA_HOME" C-m
  tmux send-keys -t nalms_$CONFIG_NAME:alarm_logger "export PATH=$JAVA_HOME/bin:$PATH" C-m
  tmux send-keys -t nalms_$CONFIG_NAME:alarm_logger "java -jar $ALARM_LOGGER_JAR -logging $LOGGING_CONFIG_FILE -properties $ALARM_LOGGER_PROPERTIES -topics $CONFIG_NAME" C-m

  # set up softIoc
  if [[ BUILD_SOFTIOC -eq 1 ]]; then

    # create softIoc file
    create-soft-iocs $CONFIG_FILE $TEMPLATE_FILE


    tmux send-keys -t nalms_$CONFIG_NAME:ioc "export JAVA_HOME=$JAVA_HOME" C-m
    tmux send-keys -t nalms_$CONFIG_NAME:ioc "export PATH=$JAVA_HOME/bin:$PATH" C-m
    tmux send-keys -t nalms_$CONFIG_NAME:ioc "export EPICS_BASE=$EPICS_BASE" C-m
    tmux send-keys -t nalms_$CONFIG_NAME:ioc "export EPICS_HOST_ARCH=$(${EPICS_BASE}/startup/EpicsHostArch)" C-m
    tmux send-keys -t nalms_$CONFIG_NAME:ioc "export PATH=${EPICS_BASE}/bin/$(${EPICS_BASE}/startup/EpicsHostArch):${PATH}" C-m
    tmux send-keys -t nalms_$CONFIG_NAME:ioc "softIoc $CMD_FILE" C-m
  fi

  #tmux $TMUX_OPTS attach-session -t nalms_$CONFIG_NAME
else
    echo "Unable to import configuration."
fi
