#!/usr/bin/env bash
set -e
export CLI_WORKDIR=$(cd $(dirname $0) && pwd)
. "$CLI_WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
Phoebus alarm services CLI
Usage: $cli_name [command]
Commands:
  start-services config_name config_file [--softIoc cmdfile]  Start all alarm services given configuration, file, and optionally hose softIoc for sevrpvs
  *         Help
"
  exit 0
}

case "$1" in
  start-services|d)
    . "$CLI_WORKDIR/commands/start-services" "$2" "$3" "$4" "5" | tee -ia "$CLI_WORKDIR/start-services_${2}.log"
    ;;
  *)
    cli_help
    ;;
esac